task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 10 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: C:/software/mydemo/DEIM/datasets/visdrone/train2017
    ann_file: C:/software/mydemo/DEIM/datasets/visdrone/annotations/instances_train2017.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: C:/software/mydemo/DEIM/datasets/visdrone/val2017
    ann_file: C:/software/mydemo/DEIM/datasets/visdrone/annotations/instances_val2017.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction

##验证测试集
#val_dataloader:
#  type: DataLoader
#  dataset:
#    type: CocoDetection
#    img_folder: C:/software/mydemo/DEIM/datasets/visdrone/test2017
#    ann_file: C:/software/mydemo/DEIM/datasets/visdrone/annotations/instances_test2017.json
#    return_masks: False
#    transforms:
#      type: Compose
#      ops: ~
#  shuffle: False
#  num_workers: 4
#  drop_last: False
#  collate_fn:
#    type: BatchImageCollateFunction